[package]
name = "vos_softfp"
version = "0.1.0"
edition = "2021"

[lib]
name         = "vos_softfp"
crate-type   = ["rlib", "cdylib"]

[profile.dev]
overflow-checks = false
opt-level = 3

[dependencies]
libc = "0.2.155"