[package]
name = "rapidlz"
version = "0.1.0"
edition = "2021"

[lib]
name         = "rapidlz"
crate-type   = ["rlib", "cdylib"]

[profile.dev]
overflow-checks = false
opt-level = 3

[dependencies]
dyn-fmt = "0.4.0"
libc = "0.2.155"
